name: .NET Core

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: restore project
      run: dotnet restore
    - name: build project
      run: dotnet build --no-incremental
    - name: restore .NET Tool
      run: dotnet tool restore
    - name: restore .NET Tool
      run: dotnet tool restore
    - name: analyze code
      run: dotnet roslynator analyze --severity-level=hidden
    - name: format code 
      run: dotnet format --check


