name: .NET Core

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: .NET Core Build
      run: ./tools/sh/dotnet_build.sh
    - name: C# Code Analyze
      run: dotnet roslynator analyze --severity-level=hidden
    - name: C# Code Format 
      run: dotnet format --check
